### ISSUE TITLE
Self dissappearing Deja-vu or keybind?

### ISSUE THREAD

**Issue by SweetyVolty** [adamk33n3r/Deja-Vu#1]
hello there, Is there any way to make plugin hide after some time like 15 secs after match starts? It's kinda annoying to stay there as the whole match or a keybind to enable/disable it?

**Comment by adamk33n3r** [comment]
Hey thanks for the idea, sorry I took so long to respond. In the meantime, you can create a keybind to toggle showing the display.

The command you should set the keybind to is `toggle cl_dejavu_visuals 0 1`

**Comment by scottismyname** [comment]
Hoping this can be addressed.  This plugin is great, but I would love for it to auto disappear after say 10-15 seconds of a match (an option would be awesome!)

**Comment by leafax** [comment]
Please, i think that a feature where it shows temporally would be a great addition, and only if you encountered the player before, and only for a certain configurable time 

also please add the link of this github on the plugin description since most player wont find it easily

**Comment by adamk33n3r** [comment]
> Please, i think that a feature where it shows temporally would be a great addition, and only if you encountered the player before, and only for a certain configurable time
> 
> also please add the link of this github on the plugin description since most player wont find it easily

I'm actually looking into the possibility of adding an option to only show the UI when looking at the scoreboard. Someone else suggested that and I think that would work for your use case as well. 

Also, the github link IS on the page. It's the Homepage button

**Comment by adamk33n3r** [comment]
Feature has been added with #4, pending release on bakkesplugins.com

**Comment by adamk33n3r** [comment]
Update is now released.
