### ISSUE TITLE
Unable to write notes, throwing errors

### ISSUE THREAD

**Issue by Ere-Eye** [adamk33n3r/Deja-Vu#10]
Since a few updates ago, whenever I open up the players' list in DejaVu, it throws a bunch of errors. Opening the quick note dialog also misbehaves. Opening the notes section from the players' list immediately results in the dialog being closed. Overall dysfunctional state. Is there something wrong on my end or is the plugin deprecated in the current version of BakkesMod?

![Dejavu Screenshot](https://user-images.githubusercontent.com/14802003/225625028-04526185-738a-4ab0-8857-e25a7ebc57e3.jpg)

**Comment by adamk33n3r** [comment]
Oh interesting, I haven't needed to touch this plugin in 2 years so it was pretty stable for a while 😂 I'll have to take a look later. Can you check the error log like the notification says and send it here?

**Comment by adamk33n3r** [comment]
[DejaVu-2.0.1.405-release.zip](https://github.com/adamk33n3r/Deja-Vu/files/10997521/DejaVu-2.0.1.405-release.zip)
Would you be willing to try this build?

**Comment by Ere-Eye** [comment]
```
[21:43:29] [bakkesmod] [class DejaVu] [json.exception.type_error.302] type must be string, but is null
[21:43:29] [bakkesmod] Got toast from DejaVu Error: Check console/log for details
```

It's this repeated. Maybe it has to do with some opponent's name that is causing problems in the json file?

The build you sent works. No error dialogs and writing notes is same as before.

Btw once I played against someone that actually knows you in person, and had asked them to pass along to you that I love your plugin!

**Comment by Ere-Eye** [comment]
> Ya it was to do with both metCount and name being null. 

So it had nothing to do with new version of BakkesMod? How did you figure out that metCount was also null? Did yours also behave the same? Since the error always expected string type, I thought it was someone's name on Steam causing problems.

> Idk how that was possible to happen, nor how it's only just now being reported after 2 years lol. But cool, I'll submit the new build to bakkesplugins.

I actually had this problem for so long actually lol. I kept putting it off because I didn't want to create an issue on Github. Tried adding and sending you a message on Discord but you had privacy settings on which is understandable. (Though your description on bakkesplugins specifically says to contact you there lmao)
Also where is the written list located at?

>Oh no way, really? That's awesome :) Was it BellyandKen?

Yes it was!! =D Super cool guy.

**Comment by adamk33n3r** [comment]
>So it had nothing to do with new version of BakkesMod? How did you figure out that metCount was also null? Did yours also behave the same? Since the error always expected string type, I thought it was someone's name on Steam causing problems.

No I don't think so. Was just with the json library I was using. But yes, my data had two entries that had both name and metCount as null. After I fixed the name issue, I was still getting the error logs so I found out that metCount was also null lol. I guess I'm grateful that I had the broken data too.

> Tried adding and sending you a message on Discord but you had privacy settings on which is understandable. (Though your description on bakkesplugins specifically says to contact you there lmao)

Ya....I was getting way too many generic bakkesmod support messages so I turned them off. But now that discord has the message request feature I'll turn it back on. I just haven't been a part of bakkesmod stuff in so long so it fell by the wayside.

>Also where is the written list located at?

What written list are you talking about?

**Comment by adamk33n3r** [comment]
[DejaVu-2.0.1.418-release.zip](https://github.com/adamk33n3r/Deja-Vu/files/11007282/DejaVu-2.0.1.418-release.zip)

I finalized my update and also updated to the latest bakkesmod sdk and had to fix a couple things. Would you be so kind as to test this build out for me? I don't have time to right now so I would be grateful! Basically the only thing that needs to be tested is that the Playlists are stilling being recorded correctly. Thanks!

**Comment by Ere-Eye** [comment]
> What written list are you talking about?

Like is the json file exported somewhere that I can look at manually outside of RL?

> Ya....I was getting way too many generic bakkesmod support messages so I turned them off. But now that discord has the message request feature I'll turn it back on. I just haven't been a part of bakkesmod stuff in so long so it fell by the wayside.

Awesome. Yeah I thought that's probably it anyway.

**Comment by adamk33n3r** [comment]
>Like is the json file exported somewhere that I can look at manually outside of RL?

Ohhh yes. It should be in your `bakkesmod/data/dejavu/player_counter.json`
