### ISSUE TITLE
Data in playlistData

### ISSUE THREAD

**Issue by TheRedRacing** [adamk33n3r/Deja-Vu#13]
Hey, I'm trying to make a website with all my data collected with the Deja-Vu plugin and I don't understand why sometimes I get : 
```json
{
    "metCount": 2,
    "name": "DarKSouL19",
    "playlistData": {
        "11": {
            "records": {
                "with": {
                    "losses": 0,
                    "wins": 2
                }
            }
        }
    },
    "timeMet": "Tue Apr 18 23:08:06 2023\n",
    "updatedAt": "Tue Apr 18 23:16:42 2023\n"
}
```
and sometimes I get : 
```json
{
    "metCount": 151,
    "name": "Panda_Kiplix",
    "playlistData": {
        "11": {
            "records": {
                "with": {
                    "losses": 40,
                    "wins": 62
                }
            }
        },
        "13": {
            "records": {
                "with": {
                    "losses": 20,
                    "wins": 26
                }
            }
        },
        "2": {
            "records": {
                "with": {
                    "losses": 0,
                    "wins": 2
                }
            }
        }
    },
    "timeMet": "Thu Aug 24 21:59:29 2023\n",
    "updatedAt": "Sun Oct  8 23:06:14 2023\n"
}
```
it's mainly numbers 11, 13, 2 that confuse me. 
Can you help me clarify this?

**Comment by TheRedRacing** [comment]
I found my answer in this file : [DejaVu.h](https://github.com/adamk33n3r/Deja-Vu/blob/57387c89924ec14acb7d7e06b6e8b3a06fa36307/DejaVu.h#L54C1-L54C1)

**Comment by adamk33n3r** [comment]
Oh hey sorry for not getting back with you, but glad you figured it out! I'd be interested to see what you're working on when it's done! :)

**Comment by TheRedRacing** [comment]
@adamk33n3r 
Now I've created a site where you can view the data that your plugin records :) Here's the link: https://rocketleague.theredracing.ch/

**Comment by adamk33n3r** [comment]
> @adamk33n3r Now I've created a site where you can view the data that your plugin records :) Here's the link: https://rocketleague.theredracing.ch/

Awesome! I just tried to use it and it doesn't seem to be working, it just reloads the page and the dialog says `The file field must be a file of type: json.` I tried another file i had that was smaller and it seemed to "work" but now it goes to `/data` and shows a 500 error page.
