### ISSUE TITLE
dejavu.log get pretty large (mine is at 213MB)

### ISSUE THREAD

**Issue by Sel-en-ium** [adamk33n3r/Deja-Vu#16]
Is it safe to delete the log contents?

**Comment by Sel-en-ium** [comment]
I'm dumb.  Just disable logging. -.-;;

**Comment by adamk33n3r** [comment]
Yes it's safe to do so, there is a LOT of logging when you have that enabled haha.

**Comment by Sel-en-ium** [comment]
@adamk33n3r Thanks for the quick response! ♥️ (Sorry for the distraction 😆)
