### ISSUE TITLE
64-Bit Update

### ISSUE THREAD

**Issue by BSBussell** [adamk33n3r/Deja-Vu#2]
Plug-in cannot currently be downloaded from the bakkes plugins website due to the recent 64-bit update.

**Comment by adamk33n3r** [comment]
Thanks for the report. I have already resubmitted the plugin to be reviewed by the team so I'll try to remember to post here when it has been released.

**Comment by adamk33n3r** [comment]
I got the notification that update has been released on bakkesplugins. Enjoy!
