### ISSUE TITLE
Players are not displaying

### ISSUE THREAD

**Issue by DualityWolfie** [adamk33n3r/Deja-Vu#3]
This doesn't happen every time, but occasionally a player won't show in the box.
No relation to PSYnet or same platform, and no relation to teammates or opponents.

I'll add ss if needed next time I notice it

**Comment by adamk33n3r** [comment]
Hey thanks for the report. I've noticed this as well, but I do think it has a relation to platform. I'm surmising that it is not tracking people playing on the Epic version. I say this because its always a player that has a "default bust" profile picture. Are you seeing this same behavior?

**Comment by adamk33n3r** [comment]
I just checked my logs and it does seem to be the case that it is Epic players. Unfortunately the bakkesmod api will need to be fixed/updated for that so it's out of my hands right now. I'll make an update here when I hear back from the core devs.

**Comment by adamk33n3r** [comment]
Just wanted to mention here that I have pushed an update that should resolve this issue. Bakkesmod finally supports tracking Epic IDs so I was able to add them into the tracking here. Let me know if you still see any issues.
