### ISSUE TITLE
Feature Request: Track Win/Loss Record

### ISSUE THREAD

**Issue by fdamstra** [adamk33n3r/Deja-Vu#7]
This is awesome. Great work! I'd love it if it also tracked wins and losses, both against the individual players and against the two as as team.

Something like:

Player | Played | Won | Lost |
------- | ------- | ----- | ----- |
EnemyA | 7 | 4 | 3 |
EnemyB |5 | 3 | 2 |
Team | 5 | 3 | 2 |
Teammate | 17 | 10 | 7 |

I expect wins + losses wouldn't always add up to played, since sometimes games crash or players swap in... Might also be nice if this only applied to competitive?

**Comment by adamk33n3r** [comment]
Unless I'm misunderstanding you, this feature already exists :) 

![image](https://user-images.githubusercontent.com/1350444/114443249-76c83300-9b9b-11eb-8ff1-1e87923e0c4a.png)

**Comment by fdamstra** [comment]
d'oh!

**Comment by adamk33n3r** [comment]
No worries! Is there something I could do/add to make that feature more noticeable?
